services:
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - next-postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - next-postgres

networks:
  next-postgres:

volumes:
  pgdata:
